<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Report Card</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; }
        .header { text-align: center; border-bottom: 3px solid #0f766e; padding-bottom: 12px; margin-bottom: 20px; }
        .school-name { font-size: 20px; font-weight: bold; color: #0f766e; }
        .student-info { margin-bottom: 20px; }
        .student-info div { margin-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
        th { background: #f3f4f6; }
        .summary { margin-top: 20px; }
        .summary div { margin-bottom: 6px; }
        .average { font-size: 18px; font-weight: bold; color: #0f766e; }
        .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">{{ $school->name }}</div>
        <div>Student Academic Report</div>
    </div>

    <div class="student-info">
        <div><strong>Student:</strong> {{ $report['student']['name'] }}</div>
        <div><strong>Student Number:</strong> {{ $report['student']['student_number'] }}</div>
        <div><strong>Class:</strong> {{ $report['student']['class_name'] }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Subject</th>
                <th>Exam</th>
                <th>Full Marks</th>
                <th>Mark</th>
                <th>Grade</th>
                <th>%</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($report['rows'] as $row)
            <tr>
                <td>{{ $row['subject'] }}</td>
                <td>{{ $row['exam_name'] }}</td>
                <td>{{ $row['full_marks'] }}</td>
                <td>{{ $row['marks'] ?? '—' }}</td>
                <td>{{ $row['grade'] ?? '—' }}</td>
                <td>{{ $row['percentage'] ?? '—' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <div><strong>Average:</strong> <span class="average">{{ $report['average'] }}%</span></div>
        <div><strong>Attendance Rate:</strong> {{ $report['attendance_rate'] }}%</div>
    </div>

    <div class="footer">
        Generated by {{ $school->name }} School System &middot; {{ now()->format('d M Y') }}
    </div>
</body>
</html>
